"""
    splitit-web-api-v3

    Splitit's API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import splitit_client
from splitit_client.model.card_data import CardData


class TestCardData(unittest.TestCase):
    """CardData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCardData(self):
        """Test CardData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CardData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
