"""
    splitit-web-api-v3

    Splitit's API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""


import sys
import unittest

import splitit_client
from splitit_client.model.identifier_contract import IdentifierContract
globals()['IdentifierContract'] = IdentifierContract
from splitit_client.model.installment_plan_update_request_by_identifier_all_of import InstallmentPlanUpdateRequestByIdentifierAllOf


class TestInstallmentPlanUpdateRequestByIdentifierAllOf(unittest.TestCase):
    """InstallmentPlanUpdateRequestByIdentifierAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstallmentPlanUpdateRequestByIdentifierAllOf(self):
        """Test InstallmentPlanUpdateRequestByIdentifierAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InstallmentPlanUpdateRequestByIdentifierAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
