/*
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Web.Net.Api;
using Splitit.Web.Net.Model;
using Splitit.Web.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Web.Net.Test.Model
{
    /// <summary>
    ///  Class for testing InitiatePlanResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InitiatePlanResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InitiatePlanResponse
        //private InitiatePlanResponse instance;

        public InitiatePlanResponseTests()
        {
            // TODO uncomment below to create an instance of InitiatePlanResponse
            //instance = new InitiatePlanResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InitiatePlanResponse
        /// </summary>
        [Fact]
        public void InitiatePlanResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" InitiatePlanResponse
            //Assert.IsType<InitiatePlanResponse>(instance);
        }


        /// <summary>
        /// Test the property 'InstallmentPlanNumber'
        /// </summary>
        [Fact]
        public void InstallmentPlanNumberTest()
        {
            // TODO unit test for the property 'InstallmentPlanNumber'
        }
        /// <summary>
        /// Test the property 'RefOrderNumber'
        /// </summary>
        [Fact]
        public void RefOrderNumberTest()
        {
            // TODO unit test for the property 'RefOrderNumber'
        }
        /// <summary>
        /// Test the property 'PurchaseMethod'
        /// </summary>
        [Fact]
        public void PurchaseMethodTest()
        {
            // TODO unit test for the property 'PurchaseMethod'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'ExtendedParams'
        /// </summary>
        [Fact]
        public void ExtendedParamsTest()
        {
            // TODO unit test for the property 'ExtendedParams'
        }
        /// <summary>
        /// Test the property 'Shopper'
        /// </summary>
        [Fact]
        public void ShopperTest()
        {
            // TODO unit test for the property 'Shopper'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'CheckoutUrl'
        /// </summary>
        [Fact]
        public void CheckoutUrlTest()
        {
            // TODO unit test for the property 'CheckoutUrl'
        }

    }

}
