/*
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Web.Net.Api;
using Splitit.Web.Net.Model;
using Splitit.Web.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Web.Net.Test.Model
{
    /// <summary>
    ///  Class for testing InstallmentPlanInitiateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InstallmentPlanInitiateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InstallmentPlanInitiateRequest
        //private InstallmentPlanInitiateRequest instance;

        public InstallmentPlanInitiateRequestTests()
        {
            // TODO uncomment below to create an instance of InstallmentPlanInitiateRequest
            //instance = new InstallmentPlanInitiateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InstallmentPlanInitiateRequest
        /// </summary>
        [Fact]
        public void InstallmentPlanInitiateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" InstallmentPlanInitiateRequest
            //Assert.IsType<InstallmentPlanInitiateRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AutoCapture'
        /// </summary>
        [Fact]
        public void AutoCaptureTest()
        {
            // TODO unit test for the property 'AutoCapture'
        }
        /// <summary>
        /// Test the property 'Attempt3dSecure'
        /// </summary>
        [Fact]
        public void Attempt3dSecureTest()
        {
            // TODO unit test for the property 'Attempt3dSecure'
        }
        /// <summary>
        /// Test the property 'Shopper'
        /// </summary>
        [Fact]
        public void ShopperTest()
        {
            // TODO unit test for the property 'Shopper'
        }
        /// <summary>
        /// Test the property 'PlanData'
        /// </summary>
        [Fact]
        public void PlanDataTest()
        {
            // TODO unit test for the property 'PlanData'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'RedirectUrls'
        /// </summary>
        [Fact]
        public void RedirectUrlsTest()
        {
            // TODO unit test for the property 'RedirectUrls'
        }

    }

}
