/*
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Web.Net.Api;
using Splitit.Web.Net.Model;
using Splitit.Web.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Web.Net.Test.Model
{
    /// <summary>
    ///  Class for testing LinksModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinksModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinksModel
        //private LinksModel instance;

        public LinksModelTests()
        {
            // TODO uncomment below to create an instance of LinksModel
            //instance = new LinksModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinksModel
        /// </summary>
        [Fact]
        public void LinksModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinksModel
            //Assert.IsType<LinksModel>(instance);
        }


        /// <summary>
        /// Test the property 'PrivacyPolicyUrl'
        /// </summary>
        [Fact]
        public void PrivacyPolicyUrlTest()
        {
            // TODO unit test for the property 'PrivacyPolicyUrl'
        }
        /// <summary>
        /// Test the property 'TermsAndConditionsUrl'
        /// </summary>
        [Fact]
        public void TermsAndConditionsUrlTest()
        {
            // TODO unit test for the property 'TermsAndConditionsUrl'
        }
        /// <summary>
        /// Test the property 'LearnMoreUrl'
        /// </summary>
        [Fact]
        public void LearnMoreUrlTest()
        {
            // TODO unit test for the property 'LearnMoreUrl'
        }

    }

}
