/*
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Web.Net.Api;
using Splitit.Web.Net.Model;
using Splitit.Web.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Web.Net.Test.Model
{
    /// <summary>
    ///  Class for testing ShopperData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShopperDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShopperData
        //private ShopperData instance;

        public ShopperDataTests()
        {
            // TODO uncomment below to create an instance of ShopperData
            //instance = new ShopperData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShopperData
        /// </summary>
        [Fact]
        public void ShopperDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShopperData
            //Assert.IsType<ShopperData>(instance);
        }


        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'Culture'
        /// </summary>
        [Fact]
        public void CultureTest()
        {
            // TODO unit test for the property 'Culture'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }

    }

}
