/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.InstallmentPlan;
import com.konfigthis.splitit.client.model.ResponseHeader;
import com.konfigthis.splitit.client.model.TransactionResult;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.splitit.client.JSON;

/**
 * InstallmentPlanResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class InstallmentPlanResponse {
  public static final String SERIALIZED_NAME_RESPONSE_HEADER = "ResponseHeader";
  @SerializedName(SERIALIZED_NAME_RESPONSE_HEADER)
  private ResponseHeader responseHeader;

  public static final String SERIALIZED_NAME_INSTALLMENT_PLAN = "InstallmentPlan";
  @SerializedName(SERIALIZED_NAME_INSTALLMENT_PLAN)
  private InstallmentPlan installmentPlan;

  public static final String SERIALIZED_NAME_GATEWAY_TRANSACTION_RESULTS = "GatewayTransactionResults";
  @SerializedName(SERIALIZED_NAME_GATEWAY_TRANSACTION_RESULTS)
  private List<TransactionResult> gatewayTransactionResults = null;

  public InstallmentPlanResponse() {
  }

  public InstallmentPlanResponse responseHeader(ResponseHeader responseHeader) {
    
    
    
    
    this.responseHeader = responseHeader;
    return this;
  }

   /**
   * Get responseHeader
   * @return responseHeader
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ResponseHeader getResponseHeader() {
    return responseHeader;
  }


  public void setResponseHeader(ResponseHeader responseHeader) {
    
    
    
    this.responseHeader = responseHeader;
  }


  public InstallmentPlanResponse installmentPlan(InstallmentPlan installmentPlan) {
    
    
    
    
    this.installmentPlan = installmentPlan;
    return this;
  }

   /**
   * Get installmentPlan
   * @return installmentPlan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InstallmentPlan getInstallmentPlan() {
    return installmentPlan;
  }


  public void setInstallmentPlan(InstallmentPlan installmentPlan) {
    
    
    
    this.installmentPlan = installmentPlan;
  }


  public InstallmentPlanResponse gatewayTransactionResults(List<TransactionResult> gatewayTransactionResults) {
    
    
    
    
    this.gatewayTransactionResults = gatewayTransactionResults;
    return this;
  }

  public InstallmentPlanResponse addGatewayTransactionResultsItem(TransactionResult gatewayTransactionResultsItem) {
    if (this.gatewayTransactionResults == null) {
      this.gatewayTransactionResults = new ArrayList<>();
    }
    this.gatewayTransactionResults.add(gatewayTransactionResultsItem);
    return this;
  }

   /**
   * Get gatewayTransactionResults
   * @return gatewayTransactionResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TransactionResult> getGatewayTransactionResults() {
    return gatewayTransactionResults;
  }


  public void setGatewayTransactionResults(List<TransactionResult> gatewayTransactionResults) {
    
    
    
    this.gatewayTransactionResults = gatewayTransactionResults;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the InstallmentPlanResponse instance itself
   */
  public InstallmentPlanResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstallmentPlanResponse installmentPlanResponse = (InstallmentPlanResponse) o;
    return Objects.equals(this.responseHeader, installmentPlanResponse.responseHeader) &&
        Objects.equals(this.installmentPlan, installmentPlanResponse.installmentPlan) &&
        Objects.equals(this.gatewayTransactionResults, installmentPlanResponse.gatewayTransactionResults)&&
        Objects.equals(this.additionalProperties, installmentPlanResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseHeader, installmentPlan, gatewayTransactionResults, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstallmentPlanResponse {\n");
    sb.append("    responseHeader: ").append(toIndentedString(responseHeader)).append("\n");
    sb.append("    installmentPlan: ").append(toIndentedString(installmentPlan)).append("\n");
    sb.append("    gatewayTransactionResults: ").append(toIndentedString(gatewayTransactionResults)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ResponseHeader");
    openapiFields.add("InstallmentPlan");
    openapiFields.add("GatewayTransactionResults");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InstallmentPlanResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InstallmentPlanResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InstallmentPlanResponse is not found in the empty JSON string", InstallmentPlanResponse.openapiRequiredFields.toString()));
        }
      }
      // validate the optional field `ResponseHeader`
      if (jsonObj.get("ResponseHeader") != null && !jsonObj.get("ResponseHeader").isJsonNull()) {
        ResponseHeader.validateJsonObject(jsonObj.getAsJsonObject("ResponseHeader"));
      }
      // validate the optional field `InstallmentPlan`
      if (jsonObj.get("InstallmentPlan") != null && !jsonObj.get("InstallmentPlan").isJsonNull()) {
        InstallmentPlan.validateJsonObject(jsonObj.getAsJsonObject("InstallmentPlan"));
      }
      if (jsonObj.get("GatewayTransactionResults") != null && !jsonObj.get("GatewayTransactionResults").isJsonNull()) {
        JsonArray jsonArraygatewayTransactionResults = jsonObj.getAsJsonArray("GatewayTransactionResults");
        if (jsonArraygatewayTransactionResults != null) {
          // ensure the json data is an array
          if (!jsonObj.get("GatewayTransactionResults").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `GatewayTransactionResults` to be an array in the JSON string but got `%s`", jsonObj.get("GatewayTransactionResults").toString()));
          }

          // validate the optional field `GatewayTransactionResults` (array)
          for (int i = 0; i < jsonArraygatewayTransactionResults.size(); i++) {
            TransactionResult.validateJsonObject(jsonArraygatewayTransactionResults.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InstallmentPlanResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InstallmentPlanResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InstallmentPlanResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InstallmentPlanResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<InstallmentPlanResponse>() {
           @Override
           public void write(JsonWriter out, InstallmentPlanResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public InstallmentPlanResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             InstallmentPlanResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InstallmentPlanResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InstallmentPlanResponse
  * @throws IOException if the JSON string is invalid with respect to InstallmentPlanResponse
  */
  public static InstallmentPlanResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InstallmentPlanResponse.class);
  }

 /**
  * Convert an instance of InstallmentPlanResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

