/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.ThreeDSData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.splitit.client.JSON;

/**
 * ProcessingData
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProcessingData {
  public static final String SERIALIZED_NAME_ATTEMPT_THREE_D_SECURED = "AttemptThreeDSecured";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_THREE_D_SECURED)
  private Boolean attemptThreeDSecured;

  public static final String SERIALIZED_NAME_SOFT_DESCRIPTOR = "SoftDescriptor";
  @SerializedName(SERIALIZED_NAME_SOFT_DESCRIPTOR)
  private String softDescriptor;

  public static final String SERIALIZED_NAME_THREE_D_S_DATA = "ThreeDSData";
  @SerializedName(SERIALIZED_NAME_THREE_D_S_DATA)
  private ThreeDSData threeDSData;

  public ProcessingData() {
  }

  public ProcessingData attemptThreeDSecured(Boolean attemptThreeDSecured) {
    
    
    
    
    this.attemptThreeDSecured = attemptThreeDSecured;
    return this;
  }

   /**
   * Get attemptThreeDSecured
   * @return attemptThreeDSecured
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAttemptThreeDSecured() {
    return attemptThreeDSecured;
  }


  public void setAttemptThreeDSecured(Boolean attemptThreeDSecured) {
    
    
    
    this.attemptThreeDSecured = attemptThreeDSecured;
  }


  public ProcessingData softDescriptor(String softDescriptor) {
    
    
    
    
    this.softDescriptor = softDescriptor;
    return this;
  }

   /**
   * Get softDescriptor
   * @return softDescriptor
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSoftDescriptor() {
    return softDescriptor;
  }


  public void setSoftDescriptor(String softDescriptor) {
    
    
    
    this.softDescriptor = softDescriptor;
  }


  public ProcessingData threeDSData(ThreeDSData threeDSData) {
    
    
    
    
    this.threeDSData = threeDSData;
    return this;
  }

   /**
   * Get threeDSData
   * @return threeDSData
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ThreeDSData getThreeDSData() {
    return threeDSData;
  }


  public void setThreeDSData(ThreeDSData threeDSData) {
    
    
    
    this.threeDSData = threeDSData;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProcessingData instance itself
   */
  public ProcessingData putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProcessingData processingData = (ProcessingData) o;
    return Objects.equals(this.attemptThreeDSecured, processingData.attemptThreeDSecured) &&
        Objects.equals(this.softDescriptor, processingData.softDescriptor) &&
        Objects.equals(this.threeDSData, processingData.threeDSData)&&
        Objects.equals(this.additionalProperties, processingData.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attemptThreeDSecured, softDescriptor, threeDSData, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProcessingData {\n");
    sb.append("    attemptThreeDSecured: ").append(toIndentedString(attemptThreeDSecured)).append("\n");
    sb.append("    softDescriptor: ").append(toIndentedString(softDescriptor)).append("\n");
    sb.append("    threeDSData: ").append(toIndentedString(threeDSData)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("AttemptThreeDSecured");
    openapiFields.add("SoftDescriptor");
    openapiFields.add("ThreeDSData");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProcessingData
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProcessingData.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProcessingData is not found in the empty JSON string", ProcessingData.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("SoftDescriptor") != null && !jsonObj.get("SoftDescriptor").isJsonNull()) && !jsonObj.get("SoftDescriptor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `SoftDescriptor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("SoftDescriptor").toString()));
      }
      // validate the optional field `ThreeDSData`
      if (jsonObj.get("ThreeDSData") != null && !jsonObj.get("ThreeDSData").isJsonNull()) {
        ThreeDSData.validateJsonObject(jsonObj.getAsJsonObject("ThreeDSData"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProcessingData.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProcessingData' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProcessingData> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProcessingData.class));

       return (TypeAdapter<T>) new TypeAdapter<ProcessingData>() {
           @Override
           public void write(JsonWriter out, ProcessingData value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProcessingData read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProcessingData instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProcessingData given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProcessingData
  * @throws IOException if the JSON string is invalid with respect to ProcessingData
  */
  public static ProcessingData fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProcessingData.class);
  }

 /**
  * Convert an instance of ProcessingData to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

