/*
 * splitit-web-api-v3
 *
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://konfigthis.com
 */


using RestSharp;

namespace Splitit.Web.Net.Client
{
    public partial class ApiClient
    {
        partial void InterceptRequest(RestRequest request) { }
    }
}
