/* DO NOT TOUCH: This file was generated by Konfig */

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum InstallmentStatus {
    PENDING = 'Pending',
    PROCESSED = 'Processed',
}
