/* DO NOT TOUCH: This file was generated by Konfig */

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { IdentifierContract } from './IdentifierContract';
import type { InstallmentPlanUpdateRequest } from './InstallmentPlanUpdateRequest';

export type InstallmentPlanUpdateRequestByIdentifier = (InstallmentPlanUpdateRequest & {
    Identifier?: IdentifierContract;
});

