/* DO NOT TOUCH: This file was generated by Konfig */

/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

import type { FailedResponse } from './FailedResponse';

export type PlanErrorResponse = (FailedResponse & {
    InstallmentPlanNumber?: string;
});

