# coding: utf-8

"""
    splitit-web-api-v3

    Splitit's Web API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from splitit_client import schemas  # noqa: F401


class InstallmentsEligibilityResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            InstallmentProvider = schemas.StrSchema
            
            
            class PaymentPlanOptions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['PaymentPlanOptionModel']:
                        return PaymentPlanOptionModel
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['PaymentPlanOptionModel'], typing.List['PaymentPlanOptionModel']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'PaymentPlanOptions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'PaymentPlanOptionModel':
                    return super().__getitem__(i)
            __annotations__ = {
                "InstallmentProvider": InstallmentProvider,
                "PaymentPlanOptions": PaymentPlanOptions,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["InstallmentProvider"]) -> MetaOapg.properties.InstallmentProvider: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["PaymentPlanOptions"]) -> MetaOapg.properties.PaymentPlanOptions: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["InstallmentProvider", "PaymentPlanOptions", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["InstallmentProvider"]) -> typing.Union[MetaOapg.properties.InstallmentProvider, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["PaymentPlanOptions"]) -> typing.Union[MetaOapg.properties.PaymentPlanOptions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["InstallmentProvider", "PaymentPlanOptions", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        InstallmentProvider: typing.Union[MetaOapg.properties.InstallmentProvider, str, schemas.Unset] = schemas.unset,
        PaymentPlanOptions: typing.Union[MetaOapg.properties.PaymentPlanOptions, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InstallmentsEligibilityResponse':
        return super().__new__(
            cls,
            *args,
            InstallmentProvider=InstallmentProvider,
            PaymentPlanOptions=PaymentPlanOptions,
            _configuration=_configuration,
            **kwargs,
        )

from splitit_client.model.payment_plan_option_model import PaymentPlanOptionModel
