/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.GwAuthorizationStatus;
import com.konfigthis.splitit.client.model.ThreeDsRedirectDataV3;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AuthorizationModel
 */
public class AuthorizationModelTest {
    private final AuthorizationModel model = new AuthorizationModel();

    /**
     * Model tests for AuthorizationModel
     */
    @Test
    public void testAuthorizationModel() {
        // TODO: test AuthorizationModel
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'splititErrorResultCode'
     */
    @Test
    public void splititErrorResultCodeTest() {
        // TODO: test splititErrorResultCode
    }

    /**
     * Test the property 'gatewayTransactionID'
     */
    @Test
    public void gatewayTransactionIDTest() {
        // TODO: test gatewayTransactionID
    }

    /**
     * Test the property 'gatewayResultCode'
     */
    @Test
    public void gatewayResultCodeTest() {
        // TODO: test gatewayResultCode
    }

    /**
     * Test the property 'gatewayResultMessage'
     */
    @Test
    public void gatewayResultMessageTest() {
        // TODO: test gatewayResultMessage
    }

    /**
     * Test the property 'threeDSRedirect'
     */
    @Test
    public void threeDSRedirectTest() {
        // TODO: test threeDSRedirect
    }

    /**
     * Test the property 'CAVV'
     */
    @Test
    public void CAVVTest() {
        // TODO: test CAVV
    }

    /**
     * Test the property 'ECI'
     */
    @Test
    public void ECITest() {
        // TODO: test ECI
    }

    /**
     * Test the property 'gatewaySourceResponse'
     */
    @Test
    public void gatewaySourceResponseTest() {
        // TODO: test gatewaySourceResponse
    }

}
