/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstallmentPlanCancelResponse
 */
public class InstallmentPlanCancelResponseTest {
    private final InstallmentPlanCancelResponse model = new InstallmentPlanCancelResponse();

    /**
     * Model tests for InstallmentPlanCancelResponse
     */
    @Test
    public void testInstallmentPlanCancelResponse() {
        // TODO: test InstallmentPlanCancelResponse
    }

    /**
     * Test the property 'installmentPlanNumber'
     */
    @Test
    public void installmentPlanNumberTest() {
        // TODO: test installmentPlanNumber
    }

}
