/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.AddressDataModel;
import com.konfigthis.splitit.client.model.EventsEndpointsModel;
import com.konfigthis.splitit.client.model.PaymentMethodModel;
import com.konfigthis.splitit.client.model.PlanDataModel;
import com.konfigthis.splitit.client.model.ProcessingData;
import com.konfigthis.splitit.client.model.RedirectionEndpointsModel;
import com.konfigthis.splitit.client.model.ShopperData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstallmentPlanCreateRequest
 */
public class InstallmentPlanCreateRequestTest {
    private final InstallmentPlanCreateRequest model = new InstallmentPlanCreateRequest();

    /**
     * Model tests for InstallmentPlanCreateRequest
     */
    @Test
    public void testInstallmentPlanCreateRequest() {
        // TODO: test InstallmentPlanCreateRequest
    }

    /**
     * Test the property 'autoCapture'
     */
    @Test
    public void autoCaptureTest() {
        // TODO: test autoCapture
    }

    /**
     * Test the property 'attempt3dSecure'
     */
    @Test
    public void attempt3dSecureTest() {
        // TODO: test attempt3dSecure
    }

    /**
     * Test the property 'termsAndConditionsAccepted'
     */
    @Test
    public void termsAndConditionsAcceptedTest() {
        // TODO: test termsAndConditionsAccepted
    }

    /**
     * Test the property 'shopper'
     */
    @Test
    public void shopperTest() {
        // TODO: test shopper
    }

    /**
     * Test the property 'planData'
     */
    @Test
    public void planDataTest() {
        // TODO: test planData
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    public void billingAddressTest() {
        // TODO: test billingAddress
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'redirectUrls'
     */
    @Test
    public void redirectUrlsTest() {
        // TODO: test redirectUrls
    }

    /**
     * Test the property 'processingData'
     */
    @Test
    public void processingDataTest() {
        // TODO: test processingData
    }

    /**
     * Test the property 'eventsEndpoints'
     */
    @Test
    public void eventsEndpointsTest() {
        // TODO: test eventsEndpoints
    }

}
