/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.IdentifierContract;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InstallmentPlanUpdateRequestByIdentifierAllOf
 */
public class InstallmentPlanUpdateRequestByIdentifierAllOfTest {
    private final InstallmentPlanUpdateRequestByIdentifierAllOf model = new InstallmentPlanUpdateRequestByIdentifierAllOf();

    /**
     * Model tests for InstallmentPlanUpdateRequestByIdentifierAllOf
     */
    @Test
    public void testInstallmentPlanUpdateRequestByIdentifierAllOf() {
        // TODO: test InstallmentPlanUpdateRequestByIdentifierAllOf
    }

    /**
     * Test the property 'identifier'
     */
    @Test
    public void identifierTest() {
        // TODO: test identifier
    }

}
