/*
 * splitit-web-api-v3
 * Splitit's Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.splitit.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.splitit.client.model.ThreeDSData2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProcessingData2
 */
public class ProcessingData2Test {
    private final ProcessingData2 model = new ProcessingData2();

    /**
     * Model tests for ProcessingData2
     */
    @Test
    public void testProcessingData2() {
        // TODO: test ProcessingData2
    }

    /**
     * Test the property 'attemptThreeDSecured'
     */
    @Test
    public void attemptThreeDSecuredTest() {
        // TODO: test attemptThreeDSecured
    }

    /**
     * Test the property 'softDescriptor'
     */
    @Test
    public void softDescriptorTest() {
        // TODO: test softDescriptor
    }

    /**
     * Test the property 'threeDSData'
     */
    @Test
    public void threeDSDataTest() {
        // TODO: test threeDSData
    }

}
