/*
splitit-web-api-v3

Splitit's Web API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReferenceEntityBase } from './reference-entity-base';

/**
 * 
 * @export
 * @interface FraudCheck
 */
export interface FraudCheck {
    /**
     * 
     * @type {ReferenceEntityBase}
     * @memberof FraudCheck
     */
    'FraudCheckResult'?: ReferenceEntityBase;
    /**
     * 
     * @type {string}
     * @memberof FraudCheck
     */
    'ProviderResultCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FraudCheck
     */
    'ProviderResultDesc'?: string;
    /**
     * 
     * @type {string}
     * @memberof FraudCheck
     */
    'ProviderReferenceId'?: string;
}

