/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-v3
 * Splitit\'s Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * https://konfigthis.com
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @enum {string}
 */

export const GwAuthorizationStatus = {
    Na: 'NA',
    Succeeded: 'Succeeded',
    Pending3Ds: 'Pending3DS',
    Failed: 'Failed'
} as const;

export type GwAuthorizationStatus = typeof GwAuthorizationStatus[keyof typeof GwAuthorizationStatus];



