/*
splitit-web-api-v3

Splitit's Web API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InitiateRedirectionEndpointsModel
 */
export interface InitiateRedirectionEndpointsModel {
    /**
     * 
     * @type {string}
     * @memberof InitiateRedirectionEndpointsModel
     */
    'Succeeded'?: string;
    /**
     * 
     * @type {string}
     * @memberof InitiateRedirectionEndpointsModel
     */
    'Failed'?: string;
    /**
     * 
     * @type {string}
     * @memberof InitiateRedirectionEndpointsModel
     */
    'Cancel'?: string;
}

