/*
splitit-web-api-v3

Splitit's Web API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SearchInstallmentPlanResponseItem } from './search-installment-plan-response-item';

/**
 * 
 * @export
 * @interface InstallmentPlanSearchResponse
 */
export interface InstallmentPlanSearchResponse {
    /**
     * 
     * @type {Array<SearchInstallmentPlanResponseItem>}
     * @memberof InstallmentPlanSearchResponse
     */
    'PlanList'?: Array<SearchInstallmentPlanResponseItem>;
}

