/* tslint:disable */
/* eslint-disable */
/**
 * splitit-web-api-v3
 * Splitit\'s Web API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PurchaseMethod } from './purchase-method';

/**
 * 
 * @export
 * @interface PlanDataModel
 */
export interface PlanDataModel {
    /**
     * The total order amount
     * @type {number}
     * @memberof PlanDataModel
     */
    'TotalAmount': number;
    /**
     * 
     * @type {string}
     * @memberof PlanDataModel
     */
    'Currency'?: string;
    /**
     * When populated will be used to display as default in Payment Form
     * @type {number}
     * @memberof PlanDataModel
     */
    'NumberOfInstallments'?: number;
    /**
     * The merchant terminal identifier
     * @type {string}
     * @memberof PlanDataModel
     */
    'TerminalId'?: string;
    /**
     * 
     * @type {PurchaseMethod}
     * @memberof PlanDataModel
     */
    'PurchaseMethod': PurchaseMethod;
    /**
     * Reference order number for merchant\'s use
     * @type {string}
     * @memberof PlanDataModel
     */
    'RefOrderNumber'?: string;
    /**
     * Additional data that can be added as key/value pair parameters by merchant (and later can be retrieved by GET)
     * @type {{ [key: string]: string; }}
     * @memberof PlanDataModel
     */
    'ExtendedParams'?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof PlanDataModel
     */
    'FirstInstallmentAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof PlanDataModel
     */
    'FirstInstallmentDate'?: string;
}

