/*
splitit-web-api-v3

Splitit's Web API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @enum {string}
 */
export type PlanStrategy = 'SecuredPlan' | 'NonSecuredPlan' | 'SecuredPlanCaptureExistingSecurityAuth' | 'SecuredPlan3' | 'SinglePayment' | 'ExternalInstallmentProvider' | 'SecuredPlan3A' | 'SecuredPlan3B' | 'SecuredPlan2A' | 'SecuredPlan2' | 'SecuredPlan4' | 'SecuredPlan4A'

