/*
splitit-web-api-v3

Splitit's Web API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { GatewayTokenData } from './gateway-token-data';

/**
 * 
 * @export
 * @interface SpreedlyToken
 */
export interface SpreedlyToken {
    /**
     * 
     * @type {string}
     * @memberof SpreedlyToken
     */
    'Token'?: string;
    /**
     * 
     * @type {string}
     * @memberof SpreedlyToken
     */
    'Last4Digit'?: string;
}

