/*
splitit-web-api-v3

Splitit's Web API

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthorizationModel } from './authorization-model';

/**
 * 
 * @export
 * @interface VerifyAuthorizationResponse
 */
export interface VerifyAuthorizationResponse {
    /**
     * 
     * @type {boolean}
     * @memberof VerifyAuthorizationResponse
     */
    'IsAuthorized': boolean;
    /**
     * 
     * @type {number}
     * @memberof VerifyAuthorizationResponse
     */
    'AuthorizationAmount'?: number;
    /**
     * 
     * @type {AuthorizationModel}
     * @memberof VerifyAuthorizationResponse
     */
    'Authorization'?: AuthorizationModel;
}

