/*
splitit-web-api-v3

Splitit's Web API

API version: 1.0.0
*/

// Code generated by Konfig (https://konfigthis.com); DO NOT EDIT.

package splitit

import (
	"encoding/json"
)

// ProcessingData2 struct for ProcessingData2
type ProcessingData2 struct {
	AttemptThreeDSecured *bool `json:"AttemptThreeDSecured,omitempty"`
	SoftDescriptor *string `json:"SoftDescriptor,omitempty"`
	ThreeDSData *ThreeDSData2 `json:"ThreeDSData,omitempty"`
}

// NewProcessingData2 instantiates a new ProcessingData2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProcessingData2() *ProcessingData2 {
	this := ProcessingData2{}
	return &this
}

// NewProcessingData2WithDefaults instantiates a new ProcessingData2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProcessingData2WithDefaults() *ProcessingData2 {
	this := ProcessingData2{}
	return &this
}

// GetAttemptThreeDSecured returns the AttemptThreeDSecured field value if set, zero value otherwise.
func (o *ProcessingData2) GetAttemptThreeDSecured() bool {
	if o == nil || isNil(o.AttemptThreeDSecured) {
		var ret bool
		return ret
	}
	return *o.AttemptThreeDSecured
}

// GetAttemptThreeDSecuredOk returns a tuple with the AttemptThreeDSecured field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessingData2) GetAttemptThreeDSecuredOk() (*bool, bool) {
	if o == nil || isNil(o.AttemptThreeDSecured) {
    return nil, false
	}
	return o.AttemptThreeDSecured, true
}

// HasAttemptThreeDSecured returns a boolean if a field has been set.
func (o *ProcessingData2) HasAttemptThreeDSecured() bool {
	if o != nil && !isNil(o.AttemptThreeDSecured) {
		return true
	}

	return false
}

// SetAttemptThreeDSecured gets a reference to the given bool and assigns it to the AttemptThreeDSecured field.
func (o *ProcessingData2) SetAttemptThreeDSecured(v bool) {
	o.AttemptThreeDSecured = &v
}

// GetSoftDescriptor returns the SoftDescriptor field value if set, zero value otherwise.
func (o *ProcessingData2) GetSoftDescriptor() string {
	if o == nil || isNil(o.SoftDescriptor) {
		var ret string
		return ret
	}
	return *o.SoftDescriptor
}

// GetSoftDescriptorOk returns a tuple with the SoftDescriptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessingData2) GetSoftDescriptorOk() (*string, bool) {
	if o == nil || isNil(o.SoftDescriptor) {
    return nil, false
	}
	return o.SoftDescriptor, true
}

// HasSoftDescriptor returns a boolean if a field has been set.
func (o *ProcessingData2) HasSoftDescriptor() bool {
	if o != nil && !isNil(o.SoftDescriptor) {
		return true
	}

	return false
}

// SetSoftDescriptor gets a reference to the given string and assigns it to the SoftDescriptor field.
func (o *ProcessingData2) SetSoftDescriptor(v string) {
	o.SoftDescriptor = &v
}

// GetThreeDSData returns the ThreeDSData field value if set, zero value otherwise.
func (o *ProcessingData2) GetThreeDSData() ThreeDSData2 {
	if o == nil || isNil(o.ThreeDSData) {
		var ret ThreeDSData2
		return ret
	}
	return *o.ThreeDSData
}

// GetThreeDSDataOk returns a tuple with the ThreeDSData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProcessingData2) GetThreeDSDataOk() (*ThreeDSData2, bool) {
	if o == nil || isNil(o.ThreeDSData) {
    return nil, false
	}
	return o.ThreeDSData, true
}

// HasThreeDSData returns a boolean if a field has been set.
func (o *ProcessingData2) HasThreeDSData() bool {
	if o != nil && !isNil(o.ThreeDSData) {
		return true
	}

	return false
}

// SetThreeDSData gets a reference to the given ThreeDSData2 and assigns it to the ThreeDSData field.
func (o *ProcessingData2) SetThreeDSData(v ThreeDSData2) {
	o.ThreeDSData = &v
}

func (o ProcessingData2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AttemptThreeDSecured) {
		toSerialize["AttemptThreeDSecured"] = o.AttemptThreeDSecured
	}
	if !isNil(o.SoftDescriptor) {
		toSerialize["SoftDescriptor"] = o.SoftDescriptor
	}
	if !isNil(o.ThreeDSData) {
		toSerialize["ThreeDSData"] = o.ThreeDSData
	}
	return json.Marshal(toSerialize)
}

type NullableProcessingData2 struct {
	value *ProcessingData2
	isSet bool
}

func (v NullableProcessingData2) Get() *ProcessingData2 {
	return v.value
}

func (v *NullableProcessingData2) Set(val *ProcessingData2) {
	v.value = val
	v.isSet = true
}

func (v NullableProcessingData2) IsSet() bool {
	return v.isSet
}

func (v *NullableProcessingData2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProcessingData2(val *ProcessingData2) *NullableProcessingData2 {
	return &NullableProcessingData2{value: val, isSet: true}
}

func (v NullableProcessingData2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProcessingData2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


