# coding: utf-8

"""
    splitit-web-api-v3

    Splitit's Web API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from splitit_client.type.installment_status import InstallmentStatus

class RequiredInstallment(TypedDict):
    InstallmentNumber: int

    Amount: typing.Union[int, float]

    Status: InstallmentStatus

class OptionalInstallment(TypedDict, total=False):
    ProcessDateTime: datetime

class Installment(RequiredInstallment, OptionalInstallment):
    pass
