# coding: utf-8

"""
    splitit-web-api-v3

    Splitit's Web API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from splitit_client.type.plan_data_allowed_installment_options import PlanDataAllowedInstallmentOptions
from splitit_client.type.plan_data_tags import PlanDataTags
from splitit_client.type.processing_data2 import ProcessingData2
from splitit_client.type.purchase_method import PurchaseMethod

class RequiredPlanData(TypedDict):
    TotalAmount: typing.Union[int, float]

    NumberOfInstallments: int

    PurchaseMethod: PurchaseMethod

class OptionalPlanData(TypedDict, total=False):
    TerminalId: str

    FirstInstallmentAmount: typing.Union[int, float]

    Currency: str

    RefOrderNumber: str

    AllowedInstallmentOptions: PlanDataAllowedInstallmentOptions

    Tags: PlanDataTags

    ProcessingData: ProcessingData2

    FirstInstallmentDate: datetime

class PlanData(RequiredPlanData, OptionalPlanData):
    pass
