# coding: utf-8

"""
    splitit-web-api-v3

    Splitit's Web API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from splitit_client.type.ux_settings_model_displayed_installment_options import UxSettingsModelDisplayedInstallmentOptions

class RequiredUxSettingsModel(TypedDict):
    pass

class OptionalUxSettingsModel(TypedDict, total=False):
    DisplayedInstallmentOptions: UxSettingsModelDisplayedInstallmentOptions

class UxSettingsModel(RequiredUxSettingsModel, OptionalUxSettingsModel):
    pass
