# coding: utf-8

"""
    splitit-web-api-v3

    Splitit's Web API

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from splitit_client.type.authorization_model import AuthorizationModel

class RequiredVerifyAuthorizationResponse(TypedDict):
    IsAuthorized: bool

class OptionalVerifyAuthorizationResponse(TypedDict, total=False):
    AuthorizationAmount: typing.Union[int, float]

    Authorization: AuthorizationModel

class VerifyAuthorizationResponse(RequiredVerifyAuthorizationResponse, OptionalVerifyAuthorizationResponse):
    pass
