/*
    * splitit-web-api-v3
    *
    * Splitit's API
    *
* The version of the OpenAPI document: 1.0.0
* 
* Generated by: https://konfigthis.com
*/


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test
{
    /// <summary>
    ///  Class for testing PlanErrorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PlanErrorResponseTests
    {
        // TODO uncomment below to declare an instance variable for PlanErrorResponse
        //private PlanErrorResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PlanErrorResponse
            //instance = new PlanErrorResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PlanErrorResponse
        /// </summary>
        [Test]
        public void PlanErrorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PlanErrorResponse
            //Assert.IsInstanceOf(typeof(PlanErrorResponse), instance);
        }


        /// <summary>
        /// Test the property 'TraceId'
        /// </summary>
        [Test]
        public void TraceIdTest()
        {
            // TODO unit test for the property 'TraceId'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'InstallmentPlanNumber'
        /// </summary>
        [Test]
        public void InstallmentPlanNumberTest()
        {
            // TODO unit test for the property 'InstallmentPlanNumber'
        }

    }

}
