/*
    * splitit-web-api-v3
    *
    * Splitit's API
    *
* The version of the OpenAPI document: 1.0.0
* 
* Generated by: https://konfigthis.com
*/


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test
{
    /// <summary>
    ///  Class for testing RedirectionEndpointsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RedirectionEndpointsModelTests
    {
        // TODO uncomment below to declare an instance variable for RedirectionEndpointsModel
        //private RedirectionEndpointsModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RedirectionEndpointsModel
            //instance = new RedirectionEndpointsModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RedirectionEndpointsModel
        /// </summary>
        [Test]
        public void RedirectionEndpointsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RedirectionEndpointsModel
            //Assert.IsInstanceOf(typeof(RedirectionEndpointsModel), instance);
        }


        /// <summary>
        /// Test the property 'AuthorizeSucceeded'
        /// </summary>
        [Test]
        public void AuthorizeSucceededTest()
        {
            // TODO unit test for the property 'AuthorizeSucceeded'
        }
        /// <summary>
        /// Test the property 'Succeeded'
        /// </summary>
        [Test]
        public void SucceededTest()
        {
            // TODO unit test for the property 'Succeeded'
        }
        /// <summary>
        /// Test the property 'AuthorizeFailed'
        /// </summary>
        [Test]
        public void AuthorizeFailedTest()
        {
            // TODO unit test for the property 'AuthorizeFailed'
        }
        /// <summary>
        /// Test the property 'Failed'
        /// </summary>
        [Test]
        public void FailedTest()
        {
            // TODO unit test for the property 'Failed'
        }

    }

}
