/*
    * splitit-web-api-v3
    *
    * Splitit's API
    *
* The version of the OpenAPI document: 1.0.0
* 
* Generated by: https://konfigthis.com
*/


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Splitit.Net.Api;
using Splitit.Net.Model;
using Splitit.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Splitit.Net.Test
{
    /// <summary>
    ///  Class for testing ThreeDsRedirectData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThreeDsRedirectDataTests
    {
        // TODO uncomment below to declare an instance variable for ThreeDsRedirectData
        //private ThreeDsRedirectData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ThreeDsRedirectData
            //instance = new ThreeDsRedirectData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ThreeDsRedirectData
        /// </summary>
        [Test]
        public void ThreeDsRedirectDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" ThreeDsRedirectData
            //Assert.IsInstanceOf(typeof(ThreeDsRedirectData), instance);
        }


        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Verb'
        /// </summary>
        [Test]
        public void VerbTest()
        {
            // TODO unit test for the property 'Verb'
        }
        /// <summary>
        /// Test the property 'Params'
        /// </summary>
        [Test]
        public void ParamsTest()
        {
            // TODO unit test for the property 'Params'
        }

    }

}
