name: konfig-poll-every-30-minutes
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    env:
      CLI_VERSION: 1.0.206
    steps:
      - uses: actions/checkout@v3
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v3
        with:
          # npm cache files are stored in "~/.npm" on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.CLI_VERSION }}
      - name: Install Konfig CLI
        run: npm install -g konfig-cli@$CLI_VERSION
      - name: Pull the latest OpenAPI Specification
        run: konfig pull
      - name: Push the OpenAPI Specification to Konfig
        run: konfig push -o konfig-dev -r splitit-web-sdks -s swagger.json
